import type { Metadata } from "next";
import { Suspense } from "react";
import SongHeading from "@/components/SongHeading";
import BackLink from "@/components/BackLink";
import NextArticle from "@/components/NextArticle";

export const metadata: Metadata = {
  title: "I'm Looking Through You — Ben Appleyard",
  description: "On the static mock, and why AI gives us a golden opportunity to leave it behind.",
};

export default function ImLookingThroughYou() {
  return (
    <main className="min-h-screen bg-surface">
      <div className="max-w-[680px] mx-auto px-6 md:px-8 pt-24 pb-32">

        <Suspense fallback={null}>
          <BackLink />
        </Suspense>

        {/* Header */}
        <div className="mb-12">
          <SongHeading
            videoId="gH6i9JAdJrQ"
            as="h1"
            className="mt-4 text-[36px] md:text-[48px] font-extrabold text-ink tracking-[-1.5px] leading-[1.1] flex items-center gap-3"
            style={{ fontFamily: "ThermalRegular", fontWeight: 400 }}
          >
            I&apos;m Looking Through You
          </SongHeading>
          <div className="mt-4 flex items-center gap-4 text-[13px] text-muted">
            <span>Feb 2026</span>
            <span>·</span>
            <span>8 min read</span>
          </div>
        </div>

        {/* Intro */}
        <p className="text-[17px] text-[#444] dark:text-[#bbb] leading-[175%]">
          I don&apos;t think I could necessarily claim to have had one issue that would constitute
          &apos;the bane of my career&apos; (so far) but if you put a gun to my head, the static
          mock might be a strong contender. I speak not of the item in and of itself, but the
          trouble that immediately cascades once it is seen by the masses.
        </p>

        <p className="mt-5 text-[17px] text-[#444] dark:text-[#bbb] leading-[175%]">
          We&apos;ve all been pondering where current AI tools are at their most powerful, when
          carefully injected into traditional design processes. I&apos;d suggest early ideation is
          where static mocks are at their most pungent. It is where I believe a profound practice
          and culture shift can take root (I&apos;m aware that in some organisations it already has).
        </p>

        {/* Section 1 */}
        <SongHeading videoId="B36yFFS55t4">Planted a Thought</SongHeading>

        <div className="space-y-5 text-[17px] text-[#444] dark:text-[#bbb] leading-[175%]">
          <p>
            A new project is underway and momentum is building. Regardless of whether this is
            taking place via waterfall, agile, AI-powered pods or some sort of intergalactic
            rocket mission, conditions are set for something impactful.
          </p>
          <p>
            The first presentation occurs: a mock is included in the latter stages of the deck,
            rapidly generated by a designer or by AI, and thus the trouble begins. Several
            questions or objections are raised upon viewing the mock; &apos;please don&apos;t put
            too much stock into this, it&apos;s purely for illustrative purposes&apos; you cry as
            you fend off the vultures, but the damage has been done. Someone has taken a screenshot
            and sent it to a stakeholder who was unable to make the meeting.
          </p>
          <p>
            Over the course of the following weeks the problem deepens. As you discuss possibilities
            and ideate with other practitioners, different variants are shared between different
            individuals. These are all taking place with the best of intentions — you&apos;re having
            a constructive conversation about the information architecture of a certain complex
            component and you need to have a healthy back and forth. But invariably, at some stage,
            one of these variants will fall into the wrong hands. Now there are multiple PMs with
            different static mocks — one has already vibecoded their interpretation of it and a
            developer has been proactively speccing from a JIRA board. You have a stakeholder
            messaging you, commenting on elements disappearing below the fold, whilst another
            stakeholder asks if you&apos;ve considered moving an icon from one side to the other.
            Perhaps worst of all, some are simply badmouthing the work for its apparent lack of
            quality.
          </p>
          <p>
            This is the very specific horror of a static mock being treated as if it were fact.
            Evidently, all of these individuals have started to form their own opinions, but the
            mock has lost all semblance of its original intent and has at no point been accompanied
            by the further context it not only deserves but needs. The static mock hasn&apos;t just
            travelled — it has metastasised.
          </p>
          <p>
            In our design world, an interface is not an image, it is a visual or auditory space of
            human interaction. The moment we represent it as an image, we have made a category
            error, and everything that follows — the misaligned or confused stakeholders, the vague
            tickets, the developer filling in gaps — is a direct consequence of that error.
          </p>
          <p>
            Marshall McLuhan, the Canadian media theorist, argued that &apos;the medium is the
            message&apos; — that the form of communication shapes its meaning more profoundly than
            the content it carries. His point was that television didn&apos;t just deliver content
            differently to radio; it changed how people thought. I wonder if perhaps the same
            principle applies here: designing in a static tool doesn&apos;t just produce static
            artefacts, it also produces static thinking. Organisations think in screens rather than
            flows, in presentation moments rather than lived experiences. Anyone that has a direct
            influence on the outcome of the interface falls into this trap.
          </p>
        </div>

        {/* Section 3 */}
        <SongHeading videoId="7IuSq4iwCtg">Travellin&apos;</SongHeading>

        <div className="space-y-5 text-[17px] text-[#444] dark:text-[#bbb] leading-[175%]">
          <p>
            I acknowledge that this problem is not equally distributed. In a small, empowered team
            — designer, engineer, PM in close proximity, shipping fast and talking constantly — the
            issue is largely self-correcting because misalignment surfaces before it calcifies; nobody is screenshotting a mock and sending it to another
            department head because there probably isn&apos;t one.
          </p>
          <p>
            In a large organisation, the hierarchy often means design has to travel upwards for
            approval before it travels to engineering. Distance between functions means a static
            mock is often the primary communication tool between people who don&apos;t share context
            (and don&apos;t understand how to). Politics means presentations become performances,
            and polished static mocks are — in a sense — a costume. These are structural features
            of how large organisations work, which is precisely what makes the discipline around
            static mocks so important in those environments. A startup can potentially be sloppy
            about this and no one bats an eyelid. A large organisation being sloppy creates
            misalignment at a scale that snowballs over months and across hundreds of people.
          </p>
          <p>
            The additional farce of a static mock is how authoritative it can look. A beautifully
            rendered image communicates: this has been thought through, this is close to done, this
            is what we are building. It&apos;s possible (perhaps even likely) that none of those
            statements are true. The polish conceals the incompleteness of the thinking behind it,
            and in an organisation where most stakeholders lack design literacy, that is a potential
            nightmare. Decisions get made, resources get allocated, expectations get set.
          </p>
        </div>

        {/* Section 4 */}
        <SongHeading videoId="OfHx-nMlXkY">Answer Code Request</SongHeading>

        <div className="space-y-5 text-[17px] text-[#444] dark:text-[#bbb] leading-[175%]">
          <p>
            A brief nod to the knock on effect from a technical perspective:
          </p>
          <p>
            When a developer receives a static mock, they receive a picture of a moment, but no
            guidance on the hundred adjacent questions that writing code requires answers to. What
            happens in the loading state? What happens when the text is twice as long? What happens
            when the API is slow, or the user&apos;s session has expired, or there are no results
            to show? What happens when the user drops their phone because their dog has snuck up on
            them? Some may fill those gaps with assumptions, and every assumption is a potential
            divergence from what the designer intended, assuming the designer had even considered it
            at all.
          </p>
          <p>
            Historically, we see this produce tight coupling: components built so specifically to
            one context shown in a mock that they resist change and resist the kind of variation
            that a real product encounters constantly. It also produces hardcoded values which
            accumulate into a codebase that becomes progressively harder to maintain.
          </p>
        </div>

        {/* Section 5 */}
        <SongHeading videoId="pXP1MSFwMnc">Out of Time</SongHeading>

        <div className="space-y-5 text-[17px] text-[#444] dark:text-[#bbb] leading-[175%]">
          <p>
            At this point, you may have what is perhaps the obvious objection: what if we don&apos;t
            have time?
          </p>
          <p>
            It is hard to dismiss this question, because I can&apos;t claim that it&apos;s
            &apos;wrong&apos; per se — depending on your workflow (and every company seems to be
            wildly different in these changing times) you may think what I&apos;m suggesting is
            wholly impractical. However, I do believe if we are measuring time, we are measuring
            the wrong thing. The time argument compares the speed of producing a static mock with
            the speed of producing a working prototype and concludes that the former is faster.
            However, it fails to account for where saved time could go.
          </p>
          <p>
            Every hour not spent on forming a working prototype is borrowed. It gets repaid — with
            interest — in back-and-forth, in rework when built reality diverges from design intent,
            in stakeholder management, in edge cases that weren&apos;t considered. Effectively, the
            static mock doesn&apos;t really save time, it just relocates it.
          </p>
          <p>
            And so to my original statement — what about the tools available now that weren&apos;t
            available two years ago? The gap in effort between producing a polished static mock and
            producing a working prototype has significantly reduced thanks to AI-powered tools. A
            designer without coding knowledge can produce a working, interactive prototype in only
            marginally more time than it previously took to design the static mock. The faster
            option and the better option have (somewhat) converged.
          </p>
        </div>

        {/* Section 6 — no artist */}
        <SongHeading videoId="jTZyG4ArBHs">Contemplation</SongHeading>

        <div className="space-y-5 text-[17px] text-[#444] dark:text-[#bbb] leading-[175%]">
          <p>Here are three things which I have actively incorporated (or am actively incorporating) into my day to day:</p>

          <ol className="list-decimal list-outside pl-5 space-y-5">
            <li>
              <strong>Being more deliberate about what I share and when.</strong>{" "}The group chat screenshot is where
              significant damage originates, and it is a cultural behaviour, which I would strongly
              argue means it is changeable. The adaptation takes time and is inherently political
              (someone will ask for a &apos;screen&apos; at some point), but it&apos;s worth it.
              Please be aware: I&apos;m not dying on this hill — I can&apos;t reasonably proclaim:
              &apos;from this day forward, I will never send another static mock again.&apos; But I
              can be far more careful.
            </li>
            <li>
              <strong>Start with prototypes to convince, not static mocks.</strong> A working prototype shown early
              creates alignment around behaviour. It is also harder to misrepresent; people are less
              likely to screenshot an interaction and pass it off as finished. The prototype forces
              the conversation to be about the right things earlier, when changing them is easy.
              Experience starts to become the currency — not images.
            </li>
            <li>
              <strong>Using AI to make this viable.</strong> The tools are endless (sometimes overwhelmingly so,
              admittedly): Figma Make, Framer AI, UX Pilot, Lovable, Bolt etc. — whatever works
              best logistically, organisationally or financially. With simple prompting, the ability
              to describe an interaction in plain language and have a working prototype emerge
              rapidly is now becoming normalised.
            </li>
          </ol>

          <p>
            A forewarning on this: I am very conscious that my argument throughout this article is
            something akin to &apos;static mocks are sloppy&apos;. The irony does not escape me
            that AI generated work is often — in and of itself — labelled as &apos;slop&apos;; if
            executed badly, prototypes can also be detrimental to productive discussion — glitchy
            transitions, incorrect content, poorly thought through journeys can all be damaging.
          </p>
          <p>
            I suppose my advice is that as long as designers are maintaining rigorous control over
            the actual interfaces and are being as deliberate as possible with their prototyping
            decisions, we begin to communicate via a medium that is so much closer to reality.
            Let&apos;s leave less to the imagination.
          </p>
        </div>

        {/* Conclusion */}
        <div className="mt-5 space-y-5 text-[17px] text-[#444] dark:text-[#bbb] leading-[175%]">
          <p>
            And so — to conclude, if design is the production of visual representations (disclaimer:
            it&apos;s not), then static mocks might work. They are fast, they are aesthetic, they are
            legible to non-designers. In many organisations, this is how design has always been
            seen and continues to be seen.
          </p>
          <p>
            If design is the authorship of experiences (disclaimer: it is) — the deliberate shaping
            of how something behaves and how it responds — then static mocks were never the right
            tool for mass communication.
          </p>
          <p>
            New tools make it easier to share the true medium of design at speed. The question in
            my eyes is not whether designers{" "}<em>should</em>{" "}move beyond the static mock for communicating
            ideas, it is whether we are willing to. I suppose if we don&apos;t, we will continue to
            field ridiculous questions about elements below the fold, and we will wonder why nobody
            seems to understand what we are trying to do.
          </p>
          <p>
            I have plenty of frustrations with thoughtless allegiance to AI, but this is one case
            where I feel we have a golden opportunity to collectively improve.
          </p>
          <p>
            For anyone who reads this, I&apos;d love to hear not only your opinion but also stories
            of how organisational initiatives have begun to impact this topic.
          </p>
        </div>

        <NextArticle
          title="The Times They Are A-Changin'"
          slug="/writing/times-they-are-a-changin"
          date="Apr 2026"
          readTime="7 min"
        />
      </div>
    </main>
  );
}
